--
-- PostgreSQL database dump
--

\restrict zIUvfvmpuFPJGYifvqmaqlf43ef5NENKiKgsKOXm2gPFg3eEeBYXuTgKY5WWUi0

-- Dumped from database version 18.0
-- Dumped by pg_dump version 18.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    username character varying(30) NOT NULL,
    address character varying(255) NOT NULL,
    balance numeric(12,2) NOT NULL,
    city character varying(100) NOT NULL,
    country character varying(100) NOT NULL,
    full_name character varying(150) NOT NULL,
    phone character varying(20) NOT NULL,
    pincode character varying(20) NOT NULL,
    state character varying(100) NOT NULL,
    gender character varying(10) NOT NULL,
    birthday date,
    instagram_link character varying(200) NOT NULL,
    facebook_link character varying(200) NOT NULL,
    email_verified boolean NOT NULL
);


ALTER TABLE public.accounts_user OWNER TO postgres;

--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_user_groups OWNER TO postgres;

--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_user_user_permissions OWNER TO postgres;

--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_chapter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_chapter (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    "order" integer NOT NULL,
    course_id bigint NOT NULL,
    CONSTRAINT courses_chapter_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.courses_chapter OWNER TO postgres;

--
-- Name: courses_chapter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_chapter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_chapter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_course; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_course (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    thumbnail character varying(100),
    price numeric(10,2) NOT NULL,
    is_published boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    instructor_id bigint
);


ALTER TABLE public.courses_course OWNER TO postgres;

--
-- Name: courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_coursecertificate; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_coursecertificate (
    id bigint NOT NULL,
    code character varying(64) NOT NULL,
    certificate_number character varying(32),
    issued_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.courses_coursecertificate OWNER TO postgres;

--
-- Name: courses_coursecertificate_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_coursecertificate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_coursecertificate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_coursecomment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_coursecomment (
    id bigint NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.courses_coursecomment OWNER TO postgres;

--
-- Name: courses_coursecomment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_coursecomment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_coursecomment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_coursereview; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_coursereview (
    id bigint NOT NULL,
    rating smallint NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT courses_coursereview_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.courses_coursereview OWNER TO postgres;

--
-- Name: courses_coursereview_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_coursereview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_coursereview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_enrollment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_enrollment (
    id bigint NOT NULL,
    enrolled_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.courses_enrollment OWNER TO postgres;

--
-- Name: courses_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_lesson; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_lesson (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    youtube_url character varying(200) NOT NULL,
    "order" integer NOT NULL,
    duration_seconds integer NOT NULL,
    chapter_id bigint NOT NULL,
    CONSTRAINT courses_lesson_duration_seconds_check CHECK ((duration_seconds >= 0)),
    CONSTRAINT courses_lesson_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.courses_lesson OWNER TO postgres;

--
-- Name: courses_lesson_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_lesson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_lesson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_lessonprogress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_lessonprogress (
    id bigint NOT NULL,
    is_completed boolean NOT NULL,
    completed_at timestamp with time zone,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.courses_lessonprogress OWNER TO postgres;

--
-- Name: courses_lessonprogress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_lessonprogress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_lessonprogress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_lessonquestion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_lessonquestion (
    id bigint NOT NULL,
    question text NOT NULL,
    answer text NOT NULL,
    answered_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    answered_by_id bigint,
    lesson_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.courses_lessonquestion OWNER TO postgres;

--
-- Name: courses_lessonquestion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_lessonquestion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_lessonquestion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses_transaction (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    trx_code character varying(100) NOT NULL,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    external_id character varying(100),
    snap_redirect_url character varying(200)
);


ALTER TABLE public.courses_transaction OWNER TO postgres;

--
-- Name: courses_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: posts_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(50) NOT NULL
);


ALTER TABLE public.posts_category OWNER TO postgres;

--
-- Name: posts_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.posts_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts_post; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts_post (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    slug character varying(300) NOT NULL,
    excerpt text NOT NULL,
    content text NOT NULL,
    thumbnail character varying(100),
    status character varying(20) NOT NULL,
    views_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    published_at timestamp with time zone,
    author_id bigint NOT NULL,
    category_id bigint,
    CONSTRAINT posts_post_views_count_check CHECK ((views_count >= 0))
);


ALTER TABLE public.posts_post OWNER TO postgres;

--
-- Name: posts_post_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.posts_post ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts_postcomment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts_postcomment (
    id bigint NOT NULL,
    rating smallint,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT posts_postcomment_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.posts_postcomment OWNER TO postgres;

--
-- Name: posts_postcomment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.posts_postcomment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_postcomment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: posts_postcommentreply; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.posts_postcommentreply (
    id bigint NOT NULL,
    message text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.posts_postcommentreply OWNER TO postgres;

--
-- Name: posts_postcommentreply_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.posts_postcommentreply ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.posts_postcommentreply_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, username, address, balance, city, country, full_name, phone, pincode, state, gender, birthday, instagram_link, facebook_link, email_verified) FROM stdin;
2	pbkdf2_sha256$1000000$SYXZtwskJWkpHgQRrqazQG$riq9XrxOmx4gb7tceXp2Q303mGf9zMcxxKznVzdwxIc=	\N	f			f	t	2026-04-11 15:40:42.968511+07	user@example.com	qwqwqzdsd	qwdsfdsfgdsfgds	342460562.20	Bigior	ddfgrg	jhon	0855542542424	102111	dsfd		\N			f
3	pbkdf2_sha256$1000000$Q4DwaEE5m4kEcAMaQDyl4c$IKV8DDZF3o3F/uySJVTto7/yJNk4p4SaD6OA/ue9zR4=	\N	f			f	t	2026-04-11 15:43:17.533759+07	sdsdfs@example.com	ddsdsdsds	string	-5283874.00	string	string	sdsdsds	085353224254	string	string		\N			f
4	pbkdf2_sha256$1000000$8wNRp2UZjKVjED3ya9zdMJ$DxXugzQUh17TlBn4GkUwhgonae95eYtu/i/xNSpBnSo=	\N	f			f	t	2026-04-11 15:46:29.702804+07	ussdser@example.com	sdsdsds		0.00			andildd	82245353535				\N			f
1	pbkdf2_sha256$1000000$HIcHlrC172GuTNqV0DiKSc$o2B/yFwPE3g+bnRLXqgrn0G/R2jTy1+4c7avMzjD3IE=	2026-04-12 15:07:51+07	t			t	t	2026-04-11 15:19:12+07	admin@gmail.com	Ust abdul		0.00								\N			f
5	pbkdf2_sha256$1000000$DeUXBYdwxfmxMoXx4PMYiz$J/eQ7NIM7c07kiQ/g2Yn6OCyn7PSCgdeJd9x+3FS6zo=	\N	f	Xie Lie	Kung	f	t	2026-04-11 18:59:10.476295+07	zainuladim555@gmail.com	dsfgfgdf	Star Apartment Beijing Building 2, Yard 30, Beixing Road	0.00	Daxing District	Indonesia	Xie Lie Kung	+62895403400605			male	2026-04-15			f
\.


--
-- Data for Name: accounts_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add enrollment	7	add_enrollment
26	Can change enrollment	7	change_enrollment
27	Can delete enrollment	7	delete_enrollment
28	Can view enrollment	7	view_enrollment
29	Can add lesson	8	add_lesson
30	Can change lesson	8	change_lesson
31	Can delete lesson	8	delete_lesson
32	Can view lesson	8	view_lesson
33	Can add transaction	9	add_transaction
34	Can change transaction	9	change_transaction
35	Can delete transaction	9	delete_transaction
36	Can view transaction	9	view_transaction
37	Can add chapter	10	add_chapter
38	Can change chapter	10	change_chapter
39	Can delete chapter	10	delete_chapter
40	Can view chapter	10	view_chapter
41	Can add course	11	add_course
42	Can change course	11	change_course
43	Can delete course	11	delete_course
44	Can view course	11	view_course
45	Can add lesson progress	12	add_lessonprogress
46	Can change lesson progress	12	change_lessonprogress
47	Can delete lesson progress	12	delete_lessonprogress
48	Can view lesson progress	12	view_lessonprogress
49	Can add category	13	add_category
50	Can change category	13	change_category
51	Can delete category	13	delete_category
52	Can view category	13	view_category
53	Can add post	14	add_post
54	Can change post	14	change_post
55	Can delete post	14	delete_post
56	Can view post	14	view_post
57	Can add course certificate	15	add_coursecertificate
58	Can change course certificate	15	change_coursecertificate
59	Can delete course certificate	15	delete_coursecertificate
60	Can view course certificate	15	view_coursecertificate
61	Can add course review	16	add_coursereview
62	Can change course review	16	change_coursereview
63	Can delete course review	16	delete_coursereview
64	Can view course review	16	view_coursereview
65	Can add course comment	17	add_coursecomment
66	Can change course comment	17	change_coursecomment
67	Can delete course comment	17	delete_coursecomment
68	Can view course comment	17	view_coursecomment
69	Can add lesson question	18	add_lessonquestion
70	Can change lesson question	18	change_lessonquestion
71	Can delete lesson question	18	delete_lessonquestion
72	Can view lesson question	18	view_lessonquestion
73	Can add post comment	19	add_postcomment
74	Can change post comment	19	change_postcomment
75	Can delete post comment	19	delete_postcomment
76	Can view post comment	19	view_postcomment
77	Can add post comment reply	20	add_postcommentreply
78	Can change post comment reply	20	change_postcommentreply
79	Can delete post comment reply	20	delete_postcommentreply
80	Can view post comment reply	20	view_postcommentreply
\.


--
-- Data for Name: courses_chapter; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_chapter (id, title, "order", course_id) FROM stdin;
3	Bab I	0	2
4	Bab I	0	3
5	Bab I	0	4
\.


--
-- Data for Name: courses_course; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_course (id, title, description, thumbnail, price, is_published, created_at, instructor_id) FROM stdin;
2	Kajian Waroqot	Kajian Waroqot merupakan kajian perdana yang menjadi langkah awal perjalanan kami dalam membangun majelis ilmu. Kajian ini berfokus pada pembahasan kitab Al-Waroqot, sebuah kitab dasar dalam ilmu ushul fiqh yang membahas prinsip-prinsip dalam memahami hukum Islam.\r\n\r\nMelalui kajian ini, peserta diajak untuk mengenal pondasi penting dalam beragama, memahami bagaimana hukum-hukum syariat ditetapkan, serta melatih cara berpikir yang sistematis dan terarah dalam menuntut ilmu.\r\n\r\nSebagai kajian pertama, Waroqot menjadi titik awal yang penuh harap—bukan hanya sebagai sarana belajar, tetapi juga sebagai wadah untuk menumbuhkan semangat menuntut ilmu, mempererat ukhuwah, dan membangun konsistensi dalam menghadiri majelis ilmu ke depannya.	courses/thumbnails/waroqot_cover.png	0.00	t	2026-04-12 15:59:08.272651+07	1
3	Kajian Awamil Jurjani	Kajian Awamil Jurjani merupakan kajian kedua dalam rangkaian majelis ilmu kami, yang berfokus pada pembahasan kitab Al-‘Awamil Al-Jurjaniyyah. Kitab ini adalah salah satu rujukan dasar dalam ilmu nahwu yang membahas tentang ‘amil (faktor yang memengaruhi perubahan akhir kata dalam bahasa Arab).\r\n\r\nMelalui kajian ini, peserta diajak untuk memahami pondasi penting dalam tata bahasa Arab, sehingga mampu membaca, memahami, dan menganalisis teks Arab dengan lebih baik dan benar.\r\n\r\nSebagai lanjutan dari kajian pertama, Awamil Jurjani diharapkan semakin menguatkan semangat belajar, memperdalam pemahaman ilmu alat, serta membangun konsistensi dalam menuntut ilmu secara bertahap dan berkelanjutan.	courses/thumbnails/awamil_cover.png	0.00	t	2026-04-12 16:36:49.596022+07	1
4	Kajian Online : Fiqih Zakat Fitrah	Kajian Fiqih Zakat Fitrah merupakan kajian ketiga dalam rangkaian majelis ilmu kami, yang membahas secara khusus tentang hukum, ketentuan, dan hikmah zakat fitrah dalam Islam.\r\n\r\nDalam kajian ini, peserta diajak untuk memahami siapa saja yang wajib mengeluarkan zakat fitrah, kepada siapa zakat tersebut diberikan, waktu pelaksanaan yang tepat, serta tata cara penunaian yang sesuai dengan syariat.\r\n\r\nKajian ini tidak hanya bersifat teoritis, tetapi juga praktis, sehingga diharapkan peserta mampu mengamalkan ilmu yang didapat dalam kehidupan sehari-hari, khususnya dalam menyempurnakan ibadah di bulan Ramadhan.\r\n\r\nSebagai kajian ketiga, materi ini menjadi pelengkap yang penting dalam membangun pemahaman fiqih dasar, sekaligus menumbuhkan kesadaran akan pentingnya berbagi dan kepedulian sosial dalam Islam.	courses/thumbnails/fiqih_cover.png	0.00	t	2026-04-12 16:58:32.690544+07	1
\.


--
-- Data for Name: courses_coursecertificate; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_coursecertificate (id, code, certificate_number, issued_at, created_at, course_id, user_id) FROM stdin;
1	c5a5b12b3edb4df5953c9d43900d97e1	BYZ-CRS-000001	2026-04-12 16:48:59.5769+07	2026-04-12 16:48:59.581478+07	2	5
\.


--
-- Data for Name: courses_coursecomment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_coursecomment (id, comment, created_at, course_id, user_id) FROM stdin;
1	bagus banget kursusnya	2026-04-12 17:39:19.574945+07	2	5
2	gKKKI	2026-04-12 18:00:39.612437+07	4	5
3	dodo	2026-04-12 18:51:03.473849+07	3	5
\.


--
-- Data for Name: courses_coursereview; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_coursereview (id, rating, comment, created_at, updated_at, course_id, user_id) FROM stdin;
1	5		2026-04-12 18:02:38.01938+07	2026-04-12 18:02:38.01938+07	2	5
\.


--
-- Data for Name: courses_enrollment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_enrollment (id, enrolled_at, course_id, user_id) FROM stdin;
2	2026-04-12 16:14:09.71367+07	2	5
3	2026-04-12 17:24:25.39199+07	3	5
\.


--
-- Data for Name: courses_lesson; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_lesson (id, title, youtube_url, "order", duration_seconds, chapter_id) FROM stdin;
2	Kajian Pertemuan 1	https://www.youtube.com/watch?v=OrvQirj9LN4&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N	0	6720	3
3	Kajian Pertemuan 2	https://www.youtube.com/watch?v=StKDiWNKD30&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=2	0	7440	3
4	Kajian Pertemuan 3	https://www.youtube.com/watch?v=FPlKvlH6t18&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=3	0	7860	3
5	Kajian Pertemuan 4	https://www.youtube.com/watch?v=l8Rh8GAzdM4&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=4	0	7380	3
6	Kajian Pertemuan 5	https://www.youtube.com/watch?v=lDuEtoOR1xo&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=5	0	7800	3
7	Kajian Pertemuan 6	https://www.youtube.com/watch?v=pc7U5Zs1IqY&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=6	0	8340	3
8	Kajian Pertemuan 7	https://www.youtube.com/watch?v=NCRwzckhYZs&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=7	0	7680	3
9	Kajian Pertemuan 8	https://www.youtube.com/watch?v=W7TlmqXMpxk&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=8	0	7380	3
10	Kajian Pertemuan 9	https://www.youtube.com/watch?v=566MG4oaSbo&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=9	0	7380	3
11	Kajian Pertemuan 10	https://www.youtube.com/watch?v=1l4i0JGV1NI&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=10	0	8220	3
12	Kajian Pertemuan 11	https://www.youtube.com/watch?v=sPEzIanXTjw&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=11	0	7680	3
13	Kajian Pertemuan 12	https://www.youtube.com/watch?v=Sp7dyzCB0e8&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=12	0	6660	3
14	Kajian Pertemuan 13	https://www.youtube.com/watch?v=ZF5zxDfwyIU&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=13	0	4860	3
15	Kajian Pertemuan 14	https://www.youtube.com/watch?v=URMhqfWxMiM&list=PLvu6KrCNreHYMNdv6Wye6CSKmSGoL8V7N&index=14	0	5640	3
16	Kajian Pertemuan 2	https://www.youtube.com/watch?v=OcQdNReaoxc&list=PLvu6KrCNreHa8pYTN6_JQACcEHgsJqeTU	0	7380	4
17	Kajian Pertemuan 3	https://www.youtube.com/watch?v=Ei5oNNC40HU&list=PLvu6KrCNreHa8pYTN6_JQACcEHgsJqeTU&index=2	0	5100	4
18	Kajian Pertemuan 4	https://www.youtube.com/watch?v=D2CFjr-WdiM&list=PLvu6KrCNreHa8pYTN6_JQACcEHgsJqeTU&index=3	0	5400	4
19	Kajian Pertemuan 5	https://www.youtube.com/watch?v=djs3mAQf1Tg&list=PLvu6KrCNreHa8pYTN6_JQACcEHgsJqeTU&index=4	0	6840	4
20	Kajian Pertemuan 6	https://www.youtube.com/watch?v=3MKfdMzggGU&list=PLvu6KrCNreHa8pYTN6_JQACcEHgsJqeTU&index=5	0	6840	4
21	Kajian Pertemuan 6	https://www.youtube.com/watch?v=WEpk3ABXLWE&list=PLvu6KrCNreHa8pYTN6_JQACcEHgsJqeTU&index=6	0	7140	4
22	Kajian Pertemuan 1	https://www.youtube.com/watch?v=5UHVqKocctY&list=PLvu6KrCNreHb6pUCsSl6wpCVXW53iLRZD&index=2	0	5280	5
23	Kajian Pertemuan 2	https://www.youtube.com/watch?v=XGdt3TEZSmw&list=PLvu6KrCNreHb6pUCsSl6wpCVXW53iLRZD&index=1	0	4560	5
\.


--
-- Data for Name: courses_lessonprogress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_lessonprogress (id, is_completed, completed_at, lesson_id, user_id) FROM stdin;
2	t	2026-04-12 16:17:38.711329+07	2	5
3	t	2026-04-12 16:47:52.315296+07	3	5
4	t	2026-04-12 16:47:57.088121+07	4	5
5	t	2026-04-12 16:48:07.540998+07	5	5
6	t	2026-04-12 16:48:12.914085+07	6	5
7	t	2026-04-12 16:48:18.072772+07	7	5
8	t	2026-04-12 16:48:24.313701+07	8	5
9	t	2026-04-12 16:48:30.041415+07	9	5
10	t	2026-04-12 16:48:34.367907+07	10	5
11	t	2026-04-12 16:48:39.752602+07	11	5
12	t	2026-04-12 16:48:43.978132+07	12	5
13	t	2026-04-12 16:48:48.688252+07	13	5
14	t	2026-04-12 16:48:54.365963+07	14	5
15	t	2026-04-12 16:48:59.573865+07	15	5
\.


--
-- Data for Name: courses_lessonquestion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_lessonquestion (id, question, answer, answered_at, created_at, answered_by_id, lesson_id, user_id) FROM stdin;
1	apa yang di maksud dengan awamil?	itu adalah	2026-04-12 18:05:04+07	2026-04-12 17:42:34.17333+07	1	16	5
\.


--
-- Data for Name: courses_transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.courses_transaction (id, amount, status, trx_code, paid_at, created_at, course_id, user_id, provider, external_id, snap_redirect_url) FROM stdin;
2	0.00	paid	TRX-B49238B3C8	2026-04-12 16:14:09.702014+07	2026-04-12 16:14:09.703541+07	2	5	balance	\N	\N
3	0.00	paid	TRX-7C0FEC17A2	2026-04-12 17:24:25.377919+07	2026-04-12 17:24:25.378426+07	3	5	balance	\N	\N
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-11 16:53:46.926096+07	1	Cara mendapatkan kasih sayang allah	1	[{"added": {}}, {"added": {"name": "chapter", "object": "Cara mendapatkan kasih sayang allah - BAB 1"}}, {"added": {"name": "chapter", "object": "Cara mendapatkan kasih sayang allah - BAB 2"}}]	11	1
2	2026-04-11 16:54:41.466862+07	1	HALLO	1	[{"added": {}}]	8	1
3	2026-04-11 16:55:36.142467+07	1	Cara mendapatkan kasih sayang allah	2	[{"changed": {"fields": ["Is published"]}}]	11	1
4	2026-04-12 12:54:17.00052+07	1	Cara mendapatkan kasih sayang allah	2	[{"changed": {"fields": ["Thumbnail"]}}]	11	1
5	2026-04-12 12:56:40.015716+07	1	apa itu islam	2	[{"changed": {"fields": ["Title", "Youtube url"]}}]	8	1
6	2026-04-12 12:58:00.28187+07	1	apa itu islam	2	[]	8	1
7	2026-04-12 15:11:47.942699+07	6	Pelajaran dari Hijrah Nabi	3		14	1
8	2026-04-12 15:11:55.076735+07	5	Hadits dan Perannya dalam Syariat	3		14	1
9	2026-04-12 15:12:02.176687+07	4	Mengenal Al-Qur'an: Petunjuk Hidup	3		14	1
10	2026-04-12 15:12:07.99694+07	3	Adab Menuntut Ilmu	3		14	1
11	2026-04-12 15:12:13.48164+07	2	Makna Ikhlas dalam Ibadah	3		14	1
12	2026-04-12 15:12:19.040856+07	1	Keutamaan Shalat Lima Waktu	3		14	1
13	2026-04-12 15:59:08.287393+07	2	Kajian Waroqot	1	[{"added": {}}, {"added": {"name": "chapter", "object": "Kajian Waroqot - Bab I"}}]	11	1
14	2026-04-12 16:12:08.233243+07	3	Kajian Waroqot - Bab I	2	[{"added": {"name": "lesson", "object": "Kajian Pertemuan 1"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 2"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 3"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 4"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 5"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 6"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 7"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 8"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 9"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 10"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 11"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 12"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 13"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 14"}}]	10	1
15	2026-04-12 16:24:44.609144+07	1	Cara mendapatkan kasih sayang allah	3		11	1
16	2026-04-12 16:36:49.610091+07	3	Kajian Awamil Jurjani	1	[{"added": {}}, {"added": {"name": "chapter", "object": "Kajian Awamil Jurjani - Kajian Awamil Jurjani I"}}]	11	1
17	2026-04-12 16:37:58.563961+07	3	Kajian Awamil Jurjani	2	[{"changed": {"name": "chapter", "object": "Kajian Awamil Jurjani - Bab I", "fields": ["Title"]}}]	11	1
18	2026-04-12 16:48:37.622437+07	4	Kajian Awamil Jurjani - Bab I	2	[{"added": {"name": "lesson", "object": "Kajian Pertemuan 2"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 3"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 4"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 5"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 6"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 6"}}]	10	1
19	2026-04-12 16:50:31.193431+07	3	Kajian Awamil Jurjani	2	[{"changed": {"fields": ["Thumbnail"]}}]	11	1
20	2026-04-12 16:58:32.702348+07	4	Kajian Online : Fiqih Zakat Fitrah	1	[{"added": {}}, {"added": {"name": "chapter", "object": "Kajian Online : Fiqih Zakat Fitrah - Bab I"}}]	11	1
21	2026-04-12 17:01:11.220758+07	5	Kajian Online : Fiqih Zakat Fitrah - Bab I	2	[{"added": {"name": "lesson", "object": "Kajian Pertemuan 1"}}, {"added": {"name": "lesson", "object": "Kajian Pertemuan 2"}}]	10	1
22	2026-04-12 17:21:14.623818+07	7	Apakah Maksiat Terjadi atas Kehendak Allah?	1	[{"added": {}}]	14	1
23	2026-04-12 17:21:20.951017+07	1	admin@gmail.com	2	[{"changed": {"fields": ["Username"]}}]	6	1
24	2026-04-12 17:57:47.683297+07	8	Harga Diri Seorang Penuntut Ilmu	1	[{"added": {}}]	14	1
25	2026-04-12 18:02:08.529531+07	9	Jika Perbedaan itu Rahmat, Lalu Apakah Sepakat itu Azab?	1	[{"added": {}}]	14	1
26	2026-04-12 18:05:06.504626+07	1	Kajian Pertemuan 2 - zainuladim555@gmail.com	2	[{"changed": {"fields": ["Answer", "Answered by", "Answered at"]}}]	18	1
27	2026-04-12 18:05:07.259683+07	10	Cinta yang Tak Terselamatkan.	1	[{"added": {}}]	14	1
28	2026-04-12 18:09:15.05407+07	11	Terlalu Sempit Memahami Rizki	1	[{"added": {}}]	14	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	accounts	user
7	courses	enrollment
8	courses	lesson
9	courses	transaction
10	courses	chapter
11	courses	course
12	courses	lessonprogress
13	posts	category
14	posts	post
15	courses	coursecertificate
16	courses	coursereview
17	courses	coursecomment
18	courses	lessonquestion
19	posts	postcomment
20	posts	postcommentreply
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-11 15:12:01.129936+07
2	contenttypes	0002_remove_content_type_name	2026-04-11 15:12:01.144539+07
3	auth	0001_initial	2026-04-11 15:12:01.197785+07
4	auth	0002_alter_permission_name_max_length	2026-04-11 15:12:01.203254+07
5	auth	0003_alter_user_email_max_length	2026-04-11 15:12:01.209286+07
6	auth	0004_alter_user_username_opts	2026-04-11 15:12:01.215973+07
7	auth	0005_alter_user_last_login_null	2026-04-11 15:12:01.221578+07
8	auth	0006_require_contenttypes_0002	2026-04-11 15:12:01.223498+07
9	auth	0007_alter_validators_add_error_messages	2026-04-11 15:12:01.229379+07
10	auth	0008_alter_user_username_max_length	2026-04-11 15:12:01.234234+07
11	auth	0009_alter_user_last_name_max_length	2026-04-11 15:12:01.241197+07
12	auth	0010_alter_group_name_max_length	2026-04-11 15:12:01.250306+07
13	auth	0011_update_proxy_permissions	2026-04-11 15:12:01.256573+07
14	auth	0012_alter_user_first_name_max_length	2026-04-11 15:12:01.261647+07
15	accounts	0001_initial	2026-04-11 15:12:01.324326+07
16	admin	0001_initial	2026-04-11 15:12:01.355152+07
17	admin	0002_logentry_remove_auto_add	2026-04-11 15:12:01.363169+07
18	admin	0003_logentry_add_action_flag_choices	2026-04-11 15:12:01.373787+07
19	sessions	0001_initial	2026-04-11 15:12:01.388309+07
20	accounts	0002_user_address_user_balance_user_city_user_country_and_more	2026-04-11 15:39:05.56712+07
21	courses	0001_initial	2026-04-11 16:33:36.893492+07
22	courses	0002_alter_course_thumbnail_add_tx_fields	2026-04-11 16:43:00.024255+07
23	courses	0003_course_instructor	2026-04-11 16:49:27.743161+07
24	courses	0004_alter_chapter_options_alter_lesson_options_and_more	2026-04-11 17:01:21.177247+07
25	posts	0001_initial	2026-04-11 17:01:21.278024+07
26	accounts	0003_user_profile_fields	2026-04-12 12:13:49.400042+07
27	posts	0002_seed_religion_categories_posts	2026-04-12 14:47:47.851528+07
28	posts	0003_alter_post_thumbnail_upload	2026-04-12 15:57:56.335429+07
29	courses	0005_coursecertificate	2026-04-12 16:40:58.939577+07
30	courses	0006_alter_coursecertificate_certificate_number	2026-04-12 16:42:26.426541+07
31	courses	0007_coursereview	2026-04-12 17:15:47.269279+07
32	courses	0008_coursecomment_lessonquestion	2026-04-12 17:29:07.888369+07
33	posts	0004_postcomment	2026-04-12 17:31:42.12515+07
34	posts	0005_postcommentreply_and_optional_rating	2026-04-12 18:09:27.856323+07
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
ptb5859348rqtgn1x7lysvmol1uf7xzt	.eJxVjDsOwjAQBe_iGln-EJmlpOcM1u56jQPIluKkirg7spQC2jczb1cRt7XErcsS56SuyqrT70bIL6kDpCfWR9Pc6rrMpIeiD9r1vSV53w7376BgL6M2Bhx4hAAC1rPzmeWSLKENgMF48ia4DELnyfiU0TFzMIFoyo5Y1OcL2bY4VQ:1wBTZ8:PjQBcslI-QcAnP2N4qgNCBNfUG2BWQdeQe1CuDT1M1s	2026-04-25 15:19:42.493291+07
uvhvz5gxgvpaxgcmu0qyv25sgp38iirm	.eJxVjDsOwjAQBe_iGln-EJmlpOcM1u56jQPIluKkirg7spQC2jczb1cRt7XErcsS56SuyqrT70bIL6kDpCfWR9Pc6rrMpIeiD9r1vSV53w7376BgL6M2Bhx4hAAC1rPzmeWSLKENgMF48ia4DELnyfiU0TFzMIFoyo5Y1OcL2bY4VQ:1wBprD:uRS7Z8DNEuRTXpn_HDvd5LddTsS_nNkQ6i9-IlLuvL0	2026-04-26 15:07:51.048202+07
\.


--
-- Data for Name: posts_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts_category (id, name, slug) FROM stdin;
1	Islam	islam
2	Aqidah	aqidah
3	Fiqh	fiqh
4	Akhlaq	akhlaq
5	Qur'an	quran
6	Hadits	hadits
7	Sejarah Islam	sejarah-islam
\.


--
-- Data for Name: posts_post; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts_post (id, title, slug, excerpt, content, thumbnail, status, views_count, created_at, updated_at, published_at, author_id, category_id) FROM stdin;
7	Apakah Maksiat Terjadi atas Kehendak Allah?	apakah-maksiat-terjadi-atas-kehendak-allah	Allah memberi kemampuan memilih, manusia menentukan pilihan, dan itu yang akan dipertanggungjawabkan	Apakah Maksiat Terjadi atas Kehendak Allah?\r\n\r\nJika iya, kenapa pelakunya disiksa?\r\n\r\nKita meyakini bahwa Allah berkehendak atas segala sesuatu yang terjadi, dan kehendak-Nya itu sempurna. Tidak ada satu pun peristiwa di alam semesta yang keluar dari aturan dan ketentuan-Nya. Kehendak Allah tidak mungkin tercampuri atau dipaksa oleh siapa pun.\r\n\r\nLalu, bagaimana dengan seseorang yang melakukan maksiat, misalnya meminum khamr? Secara nyata, ia benar-benar meminumnya. Apakah perbuatan itu terjadi dengan kehendak Allah atau tidak? Jika iya, bukankah berarti Allah menginginkan maksiat? Namun jika tidak, seakan-akan ada sesuatu yang terjadi di luar kehendak Allah.\r\n\r\nBagaimana menjawab persoalan ini?\r\n\r\nPerbuatan yang muncul dari manusia terbagi menjadi dua:\r\n\r\nPertama: perbuatan yang manusia tidak memiliki pilihan di dalamnya. Semua ini murni terjadi dengan kehendak Allah, tanpa campur tangan ikhtiar manusia. Misalnya kelahiran, kematian, sakit, sehat, atau gerakan badan ketika menggigil. Apakah kita bisa menentukan kapan ajal menjemput atau kapan tubuh merasakan sakit? Tentu tidak.\r\n\r\nKedua: perbuatan yang manusia memiliki pilihan di dalamnya. Perbuatan ini dilakukan melalui kemampuan yang Allah anugerahkan, yaitu kemampuan memilih (ikhtiar). Contohnya datang ke majelis ilmu, berdagang, atau memilih untuk melakukan maksiat.\r\n\r\nNah, di sinilah letak jawabannya.\r\n\r\nKemampuan memilih (ikhtiar) yang kita gunakan itu siapa yang memberikannya? Allah.\r\n\r\nMaka, sebenarnya Allah berkehendak agar kita menggunakan kemampuan tersebut untuk memilih. Jika kita gunakan ikhtiar untuk ketaatan, maka ketaatan itu terjadi dengan kehendak Allah. Jika kita gunakan ikhtiar untuk maksiat, maka maksiat itu pun terjadi dalam lingkup kehendak Allah.\r\n\r\nNamun, apakah dengan demikian seorang hamba boleh berkata:\r\n"Ya Allah, aku bermaksiat karena kehendak-Mu, maka janganlah Engkau siksa aku"?\r\n\r\nTentu tidak layak! Karena Allah memang menghendaki adanya pilihan, tetapi kitalah yang memilih jalan itu. Maka tanggung jawab perbuatan tetap kembali kepada manusia.	posts/thumbnails/sinan-toy-s8xjo4yjnHc-unsplash.jpg	published	9	2026-04-12 17:21:14.60967+07	2026-04-12 17:21:14.60967+07	\N	1	2
9	Jika Perbedaan itu Rahmat, Lalu Apakah Sepakat itu Azab?	jika-perbedaan-itu-rahmat-lalu-apakah-sepakat-itu-azab	Hadits “Ikhtilafu Ummati Rahmah” tidak memiliki sanad yang jelas menurut ulama seperti Imam Subki, namun ada riwayat lain yang maknanya serupa; perbedaan disebut rahmat karena memberi keluasan dalam hukum (selama di ranah cabang, bukan pokok agama); anggapan bahwa “kalau beda rahmat berarti sepakat azab” adalah keliru, dan Imam Nawawi menegaskan bahwa sesuatu disebut rahmat tidak berarti kebalikannya adalah azab.	Jika Perbedaan itu Rahmat, Lalu Apakah Sepakat itu Azab? \r\n\r\nAda sebuah hadits yang sangat masyhur tentang perbedaan pendapat. Yaitu hadits: Ikhtilafu Ummati Rahmah, yang diartikan dengan perbedaan umatku adalah rahmah, sebuah bentuk kasih sayang dari Tuhan. \r\n\r\nMenurut penelusuran Syekh Muhammad bin Ahmad Al-Ahdal dalam kitab Ifadah Al-Sadah Al-Umad, hadits ini disebutkan oleh Imam Badruddin Zarkasyi dalam kitab Al-Ahadits Al-Musytaharah yang mana di sana beliau menuliskan jika hadits ini beliau kutip dari kitab Al-Hujjah karya Syekh Nashr Al-Maqdisi. \r\n\r\nMeskipun menyebutkan sumber kutipan, tapi Imam Badruddin Zarkasyi tidak menyebutkan sanad dari hadits tersebut, tidak juga sahabat yang menjadi periwayat haditsnya. \r\n\r\nImam Subki dalam kitab Al-Halabiyyat memberikan komentar: “Hadits ini, tidak diketahui oleh ahli hadits. Saya pun belum pernah menemukan sanad hadits ini, baik sanad yang shahih, dhaif, maupun palsu. Bahkan menurut perkiraan saya, hadits ini belum ditemukan sumber aslinya.”\r\n\r\nSyekh Muhammad al-Ahdal menilai, meskipun hadits dengan lafadz tersebut belum ditemukan asalnya, bahkan sanadnya, tapi ada hadits-hadits lain yang diriwayatkan dengan makna yang sama. \r\n\r\nMisal hadits yang diriwayatkan oleh al-Thabrani juga Imam al-Baihaqi dengan sanad yang lemah: Ikhtilafu Ashabi Lakum Rahmah. (Perbedaan pendapat para sahabatku merupakan bentuk rasa kasih sayang kepada kalian). \r\n\r\nKemudian juga sebuah atsar yang mauquf kepada Al-Qasim bin Muhammad yang diriwayatkan oleh Ibn Sa'ad dan Imam Al-Baihaqi: Ikhtilafu Ashabi Muhammadin Rahmah Li Ibadil Allah. (Perbedaan sahabatnya Muhammad adalah kasih sayang bagi hamba-hamba Allah). \r\n\r\nMakna kasih sayang pada riwayat-riwayat ini, bahwa orang yang kesulitan dengan pendapat Mazhab tertentu, maka boleh baginya mengambil kemudahan dari pendapat Mazhab lain. Tentu dengan syarat-syarat yang sudah ditetapkan.\r\n\r\n**\r\n\r\nWalhasil, hadits dengan teks: Ikhtilafu Ummati Rahmah, belum ditemukan asal dan sanadnya. Meskipun begitu, ada hadits dan riwayat yang lain yang senada yang bisa kita gunakan. \r\n\r\nDi balik itu, ada beberapa orang yang keberatan dengan makna dari hadits ini. Katanya, jika perbedaan adalah rahmat, maka kesepakatan berarti adzab? \r\n\r\nImam Al-Khattabi dalam Gharib Hadits menyebut kritikan ini muncul dari pemahaman yang kurang dalam terhadap makna dari riwayat tersebut. \r\n\r\nPemahaman tersebut berasal dari Amru bin Bahr yang dikenal dengan Al-Jahidz, seorang sastrawan juga cendikiawan yang memiliki berbagai karya dalam bidang literatur Arab, Teologi, Sejarah, Filsafat, dan karya lainnya. Al-Khattabi menyebut dalam kitab tersebut, al-Jahiz sebagai orang yang tersesat dan dicurigai dalam pemahaman agamanya. \r\n\r\nOrang yang kedua adalah Ishaq bin Ibrahim al-Mushili, salah seorang musisi yang terkenal di masa Khilafah Abbasiyah. Ini dinilai oleh al-khattabi sebagai orang yang dungu dan fasiq. Meskipun ia memiliki kelihaian dalam ilmu adab dan beberapa ilmu agama, namun ia lancang menulis buku yang mencerca ahli hadits dan memberikan komentar pada makna dari riwayat perbedaan pendapat adalah rahmat. \r\n\r\nAl-Khattabi menilai orang-orang tersebut sok cerdas dengan menganggap diri mereka sebagai ulama lalu menafsirkan makna Hadits seenak keinginannya. Mereka menilai, bahwa makna dari perbedaan pendapat adalah rahmat, itu hanya berlaku pada zaman Rasulullah, saat para sahabat berbeda pendapat, lalu mereka bertanya kepada Rasulullah, dan Rasulullah langsung memberikan jawaban. Tentu pendapat mereka ini salah.\r\n\r\nMakna dari riwayat perbedaan umatku adalah rahmat merupakan kasih sayang dengan memberikan keluasan pada hukum-hukum syariat sehingga seorang muslim dapat memilih dengan syarat tertentu. Perbedaan ini hanya pada cabang hukum, bukan pada soal ushul agama.\r\n\r\nLalu jika perbedaan adalah rahmat, apakah kesepakatan adalah azab? \r\n\r\nImam Nawawi pun dalam Syarah Shahih Muslim mengomentari: menetapkan sesuatu itu rahmat, bukan berarti menetapkan kebalikan dari sesuatu itu merupakan azab.	posts/thumbnails/david-monje-8vyCtLPlEBo-unsplash.jpg	published	6	2026-04-12 18:02:08.514407+07	2026-04-12 18:02:08.514407+07	\N	1	1
8	Harga Diri Seorang Penuntut Ilmu	harga-diri-seorang-penuntut-ilmu	Menjaga harga diri adalah prinsip utama penuntut ilmu; Ali bin Abdul Aziz Al-Jurjani menolak merendahkan diri demi dunia dan dianggap tidak bergaul padahal ia menjauh dari kehinaan; ilmu harus dijaga dari sikap menjilat, ambisi dunia, dan lingkungan yang merusak martabat; jika ilmu dijaga maka ia akan menjaga pemiliknya, jika dimuliakan maka akan dimuliakan, namun jika dihinakan maka pemiliknya ikut hina; martabat ilmu bergantung pada bagaimana pembawanya menjaga diri, dan rusaknya sikap sebagian tokoh membuat orang awam enggan belajar agama.	Harga Diri Seorang Penuntut Ilmu.\r\n\r\nAli bin Abdul Aziz Al-Jurjani, seorang ulama penulis kitab al-Wasathah Baina al-Mutanabbi wa Khusumihi, yang menjaga harga dirinya sebagai ahli ilmu saat ditindas oleh kawan-kawan seangkatannya karena tidak ingin bergaul dengan gaya mereka.\r\n\r\nIa menulis sebuah Qasidah sebagai jawaban terhadap tindasan itu, sekaligus menjelaskan bagaimana seharusnya seorang ahli ilmu dalam menjaga harga diri dan martabatnya.\r\n\r\nDulu kawan-kawannya al-Jurjani suka duduk dengan para pembesar negara, memuji dan menjilat mereka, demi mendapatkan kemewahan dunia. Al-Jurjani enggan melakukan hal yang sama, hingga ia dianggap sebagai orang yang eksklusif, enggan bergaul. Dia menulis di awal Qasidahnya:\r\n\r\nيقولون لي فيك انقباض وإنما • رأو رجلا عن موقف الذل أحجما\r\n\r\n“Mereka mengatakan kepadaku, “Dirimu itu ada sifat enggan bergaul”, hanya saja mereka melihat seorang laki-laki yang sedang menjauh dari tempat yang hina”.\r\n\r\nMeski konteks Qasidah ini bercerita tentang orang yang menjauh dari pembesar negara karena enggan direndahkan demi menjaga harga dirinya, tapi makna yang disampaikan masuk ke semua sisi, apapun itu yang bisa menjatuhkan martabat seorang ahli ilmu, mulai dari cara berpakaian, tongkrongan, dan cara bicara. Semuanya harus dijaga demi menjaga kehormatan ilmu.\r\n\r\nAda dua bait yang masyhur dari Qasidah ini yang sering dikutip oleh para ulama, al-Jurjani mengatakan:\r\n\r\nولو أن أهل العلم صانوه صانهم • ولو عظموه في النفوس لعظما\r\n\r\n“seandainya ahli ilmu menjaga ilmu, maka ilmu akan menjaga mereka. Dan seandainya mereka menghormati ilmu di diri mereka, maka ilmu juga akan dihormati (oleh banyak orang).\r\n\r\nولكن أهانوه فهان ودنسوا • محياه بالأطماع حتى تجمهما\r\n\r\n“Namun mereka justru menghinakan ilmu dan akhirnya menjadi hina. Mereka mengotori tampilan ilmu dengan keinginan-keinginan kotor, sehingga ilmu tidak menarik lagi untuk dilihat.”\r\n\r\nSeolah beliau ingin bilang, bahwa ilmu itu sebetulnya sesuatu yang sangat berharga dan indah. Namun karena pemiliknya mengotori harga dirinya, dengan menggunakan ilmu untuk mendapatkan hal duniawi, dan tidak menjaga dirinya dari hal-hal yang tidak baik, akhirnya ilmu tidak lagi diminati.\r\n\r\nBetapa banyak orang awam yang kini enggan belajar agama, karena banyak tokoh agama yang gagal mempresentasikan agama sebagaimana mestinya.\r\n\r\n••\r\n\r\nHari ini saya selesai menjelaskan Qasidah karya Al-Jurjani ini, yang dikenal dengan nama Mimiyah al-Jurujani. Qasidah yang dipuji oleh al-Subki di Thabaqatnya, dan ditulis di akhir Kitab Shafahat min Shabri al-Ulama oleh Syaikh Abdul Fattah Abu Ghuddah.\r\n\r\n••\r\n6 Syawwal 1446 H.	posts/thumbnails/rizky-andar-7FldJVOe2DM-unsplash.jpg	published	3	2026-04-12 17:57:47.670464+07	2026-04-12 17:57:47.670464+07	\N	1	1
10	Cinta yang Tak Terselamatkan.	cinta-yang-tak-terselamatkan	Seorang pemuda sakit karena cinta yang dipendam, hingga melemah dan wafat di hadapan Ibnu Abbas; ia berasal dari kabilah ‘Uzrah yang dikenal dengan cinta tulus, dan kisah ini menunjukkan bahwa cinta yang dijaga dan tidak dilampiaskan bisa menjadi kemuliaan, bahkan disebut sebagai syahid.	Cinta yang Tak Terselamatkan.\r\n\r\nIbnu 'Abbas pernah dihadapkan dengan seorang pemuda yang amat kurus, pucat dan tak terurus.\r\n\r\nDia terlihat sangat lemah seolah sudah hilang sebagian nyawanya. Keluarga yang mulai cemas memohon kepada Ibnu 'Abbas: “Wahai sepupu Rasulullah, tolong obati orang ini!” \r\n\r\nIbnu 'Abbas bertanya tentang sakit yang sedang dia derita. Namun, dia hanya diam membisu dan tidak memberi jawab. \r\n\r\nBeberapa saat setelahnya dia berkata:\r\n\r\nبنا من جوى الحب المبرح لوعة\r\nتكاد  لها  نفـس  المحب  تـذوب\r\n\r\n“Dalam raga kami ada rasa kesedihan dan duka yang mendalam; karena cinta yang begitu menyakitkan bersemayam dalam jiwa. Hampir saja, jiwanya hilang, melayang karena perihnya sakit.”\r\n\r\nو  لكنما  أبلى  حشاشة  ما  ترى\r\nعلى  ما  به  عود  هنـاك  صليب\r\n\r\n“Akan tetapi, rasa itu tiap hari terus menghabisi nyawaku secara perlahan, hingga keadaanku menjadi sebagaimana yang kamu lihat. Harapannya, ia kembali ke sana, bertemu dengan orang yang telah menyalib hatinya.”\r\n\r\nMendengar itu, Ibnu Abbas terkejut dan bertanya: “dia berasal dari mana?”, keluarganya menjawab: “dia dari keluarga Uzrah.” \r\n\r\n'Uzrah adalah sebuah qabilah yang terkenal dengan cinta yang begitu tulus dan mendalam. Bagi mereka, kematian lebih ringan dari pada harus berpisah dari kekasih yang ia cintai.\r\n\r\nالموت أسهل من فراق الحبيب\r\n\r\nhingga al-Bushiri dalam Burdahnya juga menisbatkannya cintanya kepada qabilah tersebut.\r\n\r\nيا لائمي في الهوى العذري معذرة * مني إليك ولو أنصفت لم تلم.\r\n\r\n“Wahai pencaci derita cinta uzrah, kata maaf aku sampaikan padamu. Aku yakin, andai kamu merasakan derita yang sama, mungkin kamu tidak akan mencaci maki.”\r\n\r\nSetelah asal muasal keluarganya disebut, pemuda itu teriak dalam tangis. Seketika ia wafat. Kini jasadnya kaku. Dia mati dalam keadaan syahid cinta: cinta suci yang belum pernah dibalas, dan bertepuk sebelah tangan. \r\n\r\nمن عشق وكتم وعف فمات فهو شهيد \r\n\r\n“Barangsiapa yang merindu, dan dia menyembunyikannya, untuk menjaga dirinya, dan kemudian ia mati, maka ia mati syahid.”\r\n\r\n••\r\n\r\nSumber cerita kitab Izhar Sidqi al-Mawaddah. \r\n\r\n••\r\n\r\nFahrizal Fadil.	posts/thumbnails/fatih-yurur-kNSREmtaGOE-unsplash.jpg	published	2	2026-04-12 18:05:07.256653+07	2026-04-12 18:05:07.256653+07	\N	1	1
11	Terlalu Sempit Memahami Rizki	terlalu-sempit-memahami-rizki	Rizki tidak hanya soal uang dan harta, tapi juga mencakup ketenangan, ilmu, dan kesempatan dekat dengan Allah; menyempitkan makna rizki hanya pada materi bisa membuat seseorang salah paham dan kecewa; para ulama seperti Imam Al-Bukhari dan Ibnu Jarir Al-Thabari pun pernah mengalami kesulitan harta, sehingga jelas bahwa kaya atau miskin bukan ukuran nilai seseorang; semua rizki sudah ditetapkan oleh Allah dengan penuh keadilan, dan yang terpenting adalah bagaimana kita memaknainya dengan benar.	Terlalu Sempit Memahami Rizki\r\n\r\nMakna rizki oleh beberapa orang dipersempit hanya kepada materialistik. Jika banyak uang, dan harta maka banyak rizki. Jika tidak ada, maka rizkinya sedang sempit. Lalu mulai keluar sumpah serapah, mengatakan bahwa kehidupan ini tidak pernah adil. \r\n\r\nGuru kami, menyinggung santri yang berdalih dengan sebuah hadits: bahwa Allah menanggung rizki para thalib ilmi dengan rizki khusus. Ia berfikir atas hadits ini akan hidup nyaman, atau minimal suatu saat nanti akan hidup bergelimang harta. \r\n\r\nOrang memiliki pemikiran seperti ini, bisa jadi nanti ilmunya akan dikomersilkan, atau misalnya apa yang dicari selama ini tidak dapat, ia akan begitu saja meninggalkan belajar. Padahal belajar tidak ada kaitannya dengan mendapatkan harta. \r\n\r\nلو كانت الأرزاق تجري على الحجا * لهلكن إذن من جهلهن البهائم\r\n\r\n“Seandainya rizki datang sebab adanya akal (ilmu), maka pasti para binatang akan celaka dan musnah karena mereka bodoh”.\r\n\r\nSeandainya dia memahami rizki dengan makna yang semestinya. Ia akan meyakini makna hadits di atas. Rizki tidak hanya uang dan harta. Ketenangan dengan mengenal Allah, terbiasa menyebut nama Rasulullah, atau bertemu dengan banyak ulama-ulama yang teduh, juga rizki, bahkan inilah rizki khusus yang dimaksud. Di tengah banyak orang yang lalai dengan kesibukan lain selain akhirat, sedangkan thalib ilmi diberikan kesempatan yang begitu luar biasa berada di tempat tersebut. \r\n\r\nAdapun harta dan uang, semuanya sudah ditakar. Setiap orang berbeda. Ada yang alim tapi miskin, ada juga yang bodoh tapi kaya. Ada juga alim plus kaya, dan juga bodoh plus miskin. Saya teringat salah satu syahid di Hilyah Lub Masun:\r\n\r\nكم عاقل عاقل أعيت مذاهبه \r\nوجاهل  جاهل تلقاه  مـرزوقا\r\nهذا الذي ترك الأوهام  حائرة \r\nوصير  العالم النحرير  زيديقا\r\n\r\n“Berapa banyak orang cerdas yang kesulitan dalam mencari penghidupan, dan berapa banyak orang bodoh yang terlihat diberikan kemudahan. \r\n\r\nOrang bodoh ini yang membuat orang-orang bingung (kenapa bisa kaya), dan menjadikan orang yang pernah alim menjadi zindiq (karena mulai meragukan Dzat Pemberi rizki)”.\r\n\r\nPadahal jika ia sadar, bahwa semua ketentuan di alam semesta sudah digariskan oleh Tuhan, dan semuanya berada di bawah keadilan, kasih sayang, perhatian Tuhan alam semesta, tentu orang akan tenang, Ia yakin semua yang terjadi itulah terbaik.\r\n\r\nJika kita merasa alim dan merasa Allah harus memberi harta yang banyak, di mana kita dengan Imam Al-Bukhari. Diceritakan oleh Imam Al-Subki dalam kitab Thabaqat, Al-Bukhari bercerita:\r\n\r\n“Waktu aku ingin keluar menuju Imam Adam Ibn Abi Iyas di Asqalan, kiriman uang dari keluargaku telat. Sehingga saat tidak ada lagi uang, aku mulai makan rerumputan yang ada di ladang. Dan aku tidak menceritakannya ke siapapun. Waktu hari ketiga, tiba-tiba datang orang yang tidak aku kenal, lalu memberikan aku sekantong uang dan memerintah aku untuk menggunakannnya”.\r\n\r\nIbnu Jarir Al-Thabari penulis kitab Tafsir yang begitu terkenal dan tersebar manfaatnya, saat berumur 12 tahun dan ayahnya mengizinkan beliau untuk pergi belajar ke tempat yang jauh, ayahnya selalu mengirimkan uang, namun suatu saat, kiriman itu terlambat, dan ia terpaksa memotong kain baju miliknya untuk dijual! \r\n\r\nDan masih banyak lagi cerita-cerita para ulama yang merasakan kesulitan dalam urusan harta saat masa belajar, ataupun saat masa mengajar. Juga akan menemukan ulama yang kaya raya. Itu hal yang wajar-wajar saja. Sudah menjadi sunnatullah, ada si kaya dan si miskin. Dan Itu semua berada di bawah kehendak Allah.\r\n\r\n••\r\n\r\nFahrizal Fadil	posts/thumbnails/ashkan-forouzani-sfmsMZ7ezXw-unsplash.jpg	published	6	2026-04-12 18:09:15.04274+07	2026-04-12 18:09:15.04274+07	\N	1	1
\.


--
-- Data for Name: posts_postcomment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts_postcomment (id, rating, comment, created_at, updated_at, post_id, user_id) FROM stdin;
1	2	ddd	2026-04-12 17:52:07.816679+07	2026-04-12 17:55:19.48219+07	7	5
2	4	hallo	2026-04-12 18:00:06.082526+07	2026-04-12 18:00:06.082526+07	8	5
3	3	sfdsdfsdsd	2026-04-12 18:06:04.960679+07	2026-04-12 18:06:22.325824+07	9	5
\.


--
-- Data for Name: posts_postcommentreply; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.posts_postcommentreply (id, message, created_at, comment_id, user_id) FROM stdin;
\.


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_groups_id_seq', 1, false);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_id_seq', 5, true);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_user_user_permissions_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: courses_chapter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_chapter_id_seq', 5, true);


--
-- Name: courses_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_course_id_seq', 4, true);


--
-- Name: courses_coursecertificate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_coursecertificate_id_seq', 1, true);


--
-- Name: courses_coursecomment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_coursecomment_id_seq', 3, true);


--
-- Name: courses_coursereview_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_coursereview_id_seq', 1, true);


--
-- Name: courses_enrollment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_enrollment_id_seq', 3, true);


--
-- Name: courses_lesson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_lesson_id_seq', 23, true);


--
-- Name: courses_lessonprogress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_lessonprogress_id_seq', 15, true);


--
-- Name: courses_lessonquestion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_lessonquestion_id_seq', 1, true);


--
-- Name: courses_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.courses_transaction_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 28, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 34, true);


--
-- Name: posts_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_category_id_seq', 7, true);


--
-- Name: posts_post_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_post_id_seq', 11, true);


--
-- Name: posts_postcomment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_postcomment_id_seq', 3, true);


--
-- Name: posts_postcommentreply_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.posts_postcommentreply_id_seq', 1, false);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: courses_chapter courses_chapter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_chapter
    ADD CONSTRAINT courses_chapter_pkey PRIMARY KEY (id);


--
-- Name: courses_course courses_course_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_pkey PRIMARY KEY (id);


--
-- Name: courses_coursecertificate courses_coursecertificate_certificate_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecertificate
    ADD CONSTRAINT courses_coursecertificate_certificate_number_key UNIQUE (certificate_number);


--
-- Name: courses_coursecertificate courses_coursecertificate_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecertificate
    ADD CONSTRAINT courses_coursecertificate_code_key UNIQUE (code);


--
-- Name: courses_coursecertificate courses_coursecertificate_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecertificate
    ADD CONSTRAINT courses_coursecertificate_pkey PRIMARY KEY (id);


--
-- Name: courses_coursecertificate courses_coursecertificate_user_id_course_id_52255782_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecertificate
    ADD CONSTRAINT courses_coursecertificate_user_id_course_id_52255782_uniq UNIQUE (user_id, course_id);


--
-- Name: courses_coursecomment courses_coursecomment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecomment
    ADD CONSTRAINT courses_coursecomment_pkey PRIMARY KEY (id);


--
-- Name: courses_coursereview courses_coursereview_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursereview
    ADD CONSTRAINT courses_coursereview_pkey PRIMARY KEY (id);


--
-- Name: courses_coursereview courses_coursereview_user_id_course_id_f21a28f1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursereview
    ADD CONSTRAINT courses_coursereview_user_id_course_id_f21a28f1_uniq UNIQUE (user_id, course_id);


--
-- Name: courses_enrollment courses_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_enrollment
    ADD CONSTRAINT courses_enrollment_pkey PRIMARY KEY (id);


--
-- Name: courses_enrollment courses_enrollment_user_id_course_id_7c8ca1bf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_enrollment
    ADD CONSTRAINT courses_enrollment_user_id_course_id_7c8ca1bf_uniq UNIQUE (user_id, course_id);


--
-- Name: courses_lesson courses_lesson_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lesson
    ADD CONSTRAINT courses_lesson_pkey PRIMARY KEY (id);


--
-- Name: courses_lessonprogress courses_lessonprogress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonprogress
    ADD CONSTRAINT courses_lessonprogress_pkey PRIMARY KEY (id);


--
-- Name: courses_lessonprogress courses_lessonprogress_user_id_lesson_id_940f22e7_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonprogress
    ADD CONSTRAINT courses_lessonprogress_user_id_lesson_id_940f22e7_uniq UNIQUE (user_id, lesson_id);


--
-- Name: courses_lessonquestion courses_lessonquestion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonquestion
    ADD CONSTRAINT courses_lessonquestion_pkey PRIMARY KEY (id);


--
-- Name: courses_transaction courses_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_transaction
    ADD CONSTRAINT courses_transaction_pkey PRIMARY KEY (id);


--
-- Name: courses_transaction courses_transaction_trx_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_transaction
    ADD CONSTRAINT courses_transaction_trx_code_key UNIQUE (trx_code);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: posts_category posts_category_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_category
    ADD CONSTRAINT posts_category_name_key UNIQUE (name);


--
-- Name: posts_category posts_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_category
    ADD CONSTRAINT posts_category_pkey PRIMARY KEY (id);


--
-- Name: posts_category posts_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_category
    ADD CONSTRAINT posts_category_slug_key UNIQUE (slug);


--
-- Name: posts_post posts_post_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_post
    ADD CONSTRAINT posts_post_pkey PRIMARY KEY (id);


--
-- Name: posts_post posts_post_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_post
    ADD CONSTRAINT posts_post_slug_key UNIQUE (slug);


--
-- Name: posts_postcomment posts_postcomment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcomment
    ADD CONSTRAINT posts_postcomment_pkey PRIMARY KEY (id);


--
-- Name: posts_postcomment posts_postcomment_post_id_user_id_7e734afe_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcomment
    ADD CONSTRAINT posts_postcomment_post_id_user_id_7e734afe_uniq UNIQUE (post_id, user_id);


--
-- Name: posts_postcommentreply posts_postcommentreply_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcommentreply
    ADD CONSTRAINT posts_postcommentreply_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: courses_chapter_course_id_24d15099; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_chapter_course_id_24d15099 ON public.courses_chapter USING btree (course_id);


--
-- Name: courses_course_instructor_id_5b0643dc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_course_instructor_id_5b0643dc ON public.courses_course USING btree (instructor_id);


--
-- Name: courses_coursecertificate_certificate_number_0602304c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursecertificate_certificate_number_0602304c_like ON public.courses_coursecertificate USING btree (certificate_number varchar_pattern_ops);


--
-- Name: courses_coursecertificate_code_63946be3_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursecertificate_code_63946be3_like ON public.courses_coursecertificate USING btree (code varchar_pattern_ops);


--
-- Name: courses_coursecertificate_course_id_365adbe6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursecertificate_course_id_365adbe6 ON public.courses_coursecertificate USING btree (course_id);


--
-- Name: courses_coursecertificate_user_id_db9038e8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursecertificate_user_id_db9038e8 ON public.courses_coursecertificate USING btree (user_id);


--
-- Name: courses_coursecomment_course_id_30471d45; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursecomment_course_id_30471d45 ON public.courses_coursecomment USING btree (course_id);


--
-- Name: courses_coursecomment_user_id_12d297fb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursecomment_user_id_12d297fb ON public.courses_coursecomment USING btree (user_id);


--
-- Name: courses_coursereview_course_id_15681ba3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursereview_course_id_15681ba3 ON public.courses_coursereview USING btree (course_id);


--
-- Name: courses_coursereview_user_id_7838c5d6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_coursereview_user_id_7838c5d6 ON public.courses_coursereview USING btree (user_id);


--
-- Name: courses_enrollment_course_id_2631503e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_enrollment_course_id_2631503e ON public.courses_enrollment USING btree (course_id);


--
-- Name: courses_enrollment_user_id_da3de16f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_enrollment_user_id_da3de16f ON public.courses_enrollment USING btree (user_id);


--
-- Name: courses_lesson_chapter_id_401d021a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_lesson_chapter_id_401d021a ON public.courses_lesson USING btree (chapter_id);


--
-- Name: courses_lessonprogress_lesson_id_b0b36960; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_lessonprogress_lesson_id_b0b36960 ON public.courses_lessonprogress USING btree (lesson_id);


--
-- Name: courses_lessonprogress_user_id_f1d37bb4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_lessonprogress_user_id_f1d37bb4 ON public.courses_lessonprogress USING btree (user_id);


--
-- Name: courses_lessonquestion_answered_by_id_cb1df4f4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_lessonquestion_answered_by_id_cb1df4f4 ON public.courses_lessonquestion USING btree (answered_by_id);


--
-- Name: courses_lessonquestion_lesson_id_2ddee1f8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_lessonquestion_lesson_id_2ddee1f8 ON public.courses_lessonquestion USING btree (lesson_id);


--
-- Name: courses_lessonquestion_user_id_979f42db; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_lessonquestion_user_id_979f42db ON public.courses_lessonquestion USING btree (user_id);


--
-- Name: courses_transaction_course_id_a684bda2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_transaction_course_id_a684bda2 ON public.courses_transaction USING btree (course_id);


--
-- Name: courses_transaction_trx_code_26c462b6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_transaction_trx_code_26c462b6_like ON public.courses_transaction USING btree (trx_code varchar_pattern_ops);


--
-- Name: courses_transaction_user_id_de60bb97; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX courses_transaction_user_id_de60bb97 ON public.courses_transaction USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: posts_category_name_3f7ad975_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_category_name_3f7ad975_like ON public.posts_category USING btree (name varchar_pattern_ops);


--
-- Name: posts_category_slug_8145c8e7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_category_slug_8145c8e7_like ON public.posts_category USING btree (slug varchar_pattern_ops);


--
-- Name: posts_post_author_id_fe5487bf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_post_author_id_fe5487bf ON public.posts_post USING btree (author_id);


--
-- Name: posts_post_category_id_ab339803; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_post_category_id_ab339803 ON public.posts_post USING btree (category_id);


--
-- Name: posts_post_slug_6e9097e5_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_post_slug_6e9097e5_like ON public.posts_post USING btree (slug varchar_pattern_ops);


--
-- Name: posts_postcomment_post_id_5b40467f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_postcomment_post_id_5b40467f ON public.posts_postcomment USING btree (post_id);


--
-- Name: posts_postcomment_user_id_85b4cbc4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_postcomment_user_id_85b4cbc4 ON public.posts_postcomment USING btree (user_id);


--
-- Name: posts_postcommentreply_comment_id_df75c45d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_postcommentreply_comment_id_df75c45d ON public.posts_postcommentreply USING btree (comment_id);


--
-- Name: posts_postcommentreply_user_id_5a0ca837; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX posts_postcommentreply_user_id_5a0ca837 ON public.posts_postcommentreply USING btree (user_id);


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_chapter courses_chapter_course_id_24d15099_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_chapter
    ADD CONSTRAINT courses_chapter_course_id_24d15099_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_course courses_course_instructor_id_5b0643dc_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_course
    ADD CONSTRAINT courses_course_instructor_id_5b0643dc_fk_accounts_user_id FOREIGN KEY (instructor_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursecertificate courses_coursecertif_course_id_365adbe6_fk_courses_c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecertificate
    ADD CONSTRAINT courses_coursecertif_course_id_365adbe6_fk_courses_c FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursecertificate courses_coursecertificate_user_id_db9038e8_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecertificate
    ADD CONSTRAINT courses_coursecertificate_user_id_db9038e8_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursecomment courses_coursecomment_course_id_30471d45_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecomment
    ADD CONSTRAINT courses_coursecomment_course_id_30471d45_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursecomment courses_coursecomment_user_id_12d297fb_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursecomment
    ADD CONSTRAINT courses_coursecomment_user_id_12d297fb_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursereview courses_coursereview_course_id_15681ba3_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursereview
    ADD CONSTRAINT courses_coursereview_course_id_15681ba3_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_coursereview courses_coursereview_user_id_7838c5d6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_coursereview
    ADD CONSTRAINT courses_coursereview_user_id_7838c5d6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_enrollment courses_enrollment_course_id_2631503e_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_enrollment
    ADD CONSTRAINT courses_enrollment_course_id_2631503e_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_enrollment courses_enrollment_user_id_da3de16f_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_enrollment
    ADD CONSTRAINT courses_enrollment_user_id_da3de16f_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lesson courses_lesson_chapter_id_401d021a_fk_courses_chapter_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lesson
    ADD CONSTRAINT courses_lesson_chapter_id_401d021a_fk_courses_chapter_id FOREIGN KEY (chapter_id) REFERENCES public.courses_chapter(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lessonprogress courses_lessonprogress_lesson_id_b0b36960_fk_courses_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonprogress
    ADD CONSTRAINT courses_lessonprogress_lesson_id_b0b36960_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lessonprogress courses_lessonprogress_user_id_f1d37bb4_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonprogress
    ADD CONSTRAINT courses_lessonprogress_user_id_f1d37bb4_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lessonquestion courses_lessonquesti_answered_by_id_cb1df4f4_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonquestion
    ADD CONSTRAINT courses_lessonquesti_answered_by_id_cb1df4f4_fk_accounts_ FOREIGN KEY (answered_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lessonquestion courses_lessonquestion_lesson_id_2ddee1f8_fk_courses_lesson_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonquestion
    ADD CONSTRAINT courses_lessonquestion_lesson_id_2ddee1f8_fk_courses_lesson_id FOREIGN KEY (lesson_id) REFERENCES public.courses_lesson(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_lessonquestion courses_lessonquestion_user_id_979f42db_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_lessonquestion
    ADD CONSTRAINT courses_lessonquestion_user_id_979f42db_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_transaction courses_transaction_course_id_a684bda2_fk_courses_course_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_transaction
    ADD CONSTRAINT courses_transaction_course_id_a684bda2_fk_courses_course_id FOREIGN KEY (course_id) REFERENCES public.courses_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: courses_transaction courses_transaction_user_id_de60bb97_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses_transaction
    ADD CONSTRAINT courses_transaction_user_id_de60bb97_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: posts_post posts_post_author_id_fe5487bf_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_post
    ADD CONSTRAINT posts_post_author_id_fe5487bf_fk_accounts_user_id FOREIGN KEY (author_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: posts_post posts_post_category_id_ab339803_fk_posts_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_post
    ADD CONSTRAINT posts_post_category_id_ab339803_fk_posts_category_id FOREIGN KEY (category_id) REFERENCES public.posts_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: posts_postcomment posts_postcomment_post_id_5b40467f_fk_posts_post_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcomment
    ADD CONSTRAINT posts_postcomment_post_id_5b40467f_fk_posts_post_id FOREIGN KEY (post_id) REFERENCES public.posts_post(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: posts_postcomment posts_postcomment_user_id_85b4cbc4_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcomment
    ADD CONSTRAINT posts_postcomment_user_id_85b4cbc4_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: posts_postcommentreply posts_postcommentrep_comment_id_df75c45d_fk_posts_pos; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcommentreply
    ADD CONSTRAINT posts_postcommentrep_comment_id_df75c45d_fk_posts_pos FOREIGN KEY (comment_id) REFERENCES public.posts_postcomment(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: posts_postcommentreply posts_postcommentreply_user_id_5a0ca837_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.posts_postcommentreply
    ADD CONSTRAINT posts_postcommentreply_user_id_5a0ca837_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict zIUvfvmpuFPJGYifvqmaqlf43ef5NENKiKgsKOXm2gPFg3eEeBYXuTgKY5WWUi0

